# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'YYxReceipt' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YYxReceipt
	pod 'SnapKit'
	pod 'EasyAnimation'
	pod 'AFDateHelper'
	pod 'Toaster', '~> 2.0'
	pod 'Alamofire', '~> 4.0'
	pod 'SwiftyJSON'
end
